Release: 
	g++ -g `wx-config --cxxflags` `wx-config --libs`  `pkg-config --cflags gtk+-2.0` `pkg-config --libs gtk+-2.0` -I/usr/local/include/whiteHawk/system/ src/*.cpp -lX11 -lwhsystem -o Taskbar -lzzip

